<!DOCTYPE html>
<html lang="zh-CN" class="h-full bg-gray-950">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= $title ?? 'OnePage - 现代网页分享' ?></title>
    <!-- Favicon package generated by Favicon.im Generator -->
    <link rel="icon" type="image/x-icon" href="../favicon.ico">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    <script src="https://cdn.tailwindcss.com"></script>
    <style>
        @font-face {
            font-family: 'CangErYuMoW02-2';
            src: url('/ttf/CangErYuMoW02-2.ttf') format('truetype');
            font-display: swap;
        }
        body { font-family: 'Microsoft YaHei', 'PingFang SC', 'Hiragino Sans GB', 'WenQuanYi Micro Hei', sans-serif; cursor: default; }
        .glass { background: rgba(15, 15, 20, 0.7); backdrop-filter: blur(16px); border: 1px solid rgba(255, 255, 255, 0.08); }
        .gradient-text { background: linear-gradient(135deg, #fff 0%, #a855f7 50%, #6366f1 100%); -webkit-background-clip: text; -webkit-text-fill-color: transparent; }
        
        .glow-card:hover { box-shadow: 0 0 40px rgba(168, 85, 247, 0.15); border-color: rgba(168, 85, 247, 0.3); }
        
        @keyframes float { 0% { transform: translateY(0px); } 50% { transform: translateY(-10px); } 100% { transform: translateY(0px); } }
        .animate-float { animation: float 6s ease-in-out infinite; }
        
        @keyframes subtle-pulse { 0%, 100% { opacity: 0.8; } 50% { opacity: 1; } }
        .animate-subtle { animation: subtle-pulse 4s ease-in-out infinite; }

        /* Custom Scrollbar */
        ::-webkit-scrollbar { width: 6px; }
        ::-webkit-scrollbar-track { background: #0f172a; }
        ::-webkit-scrollbar-thumb { background: #334155; border-radius: 10px; }
        ::-webkit-scrollbar-thumb:hover { background: #475569; }

        /* Scroll Animation */
        .fade-in-up {
            opacity: 0;
            transform: translateY(50px);
            transition: opacity 0.8s ease, transform 0.8s ease;
        }
        .fade-in-up.animate {
            opacity: 1;
            transform: translateY(0);
        }
        .fade-in-up.delay-200 { transition-delay: 0.2s; }
        .fade-in-up.delay-400 { transition-delay: 0.4s; }

        /* Switch Button */
        .switch-button {
          display: -webkit-box;
          display: -ms-flexbox;
          display: flex;
          -webkit-box-align: center;
          align-items: center;
          -webkit-box-pack: center;
          justify-content: center;
          justify-content: center;
          margin: auto;
          height: 55px;
        }

        .switch-button .switch-outer {
          height: 100%;
          background: #252532;
          width: 115px;
          border-radius: 165px;
          -webkit-box-shadow: inset 0px 5px 10px 0px #16151c, 0px 3px 6px -2px #403f4e;
          box-shadow: inset 0px 5px 10px 0px #16151c, 0px 3px 6px -2px #403f4e;
          border: 1px solid #32303e;
          padding: 6px;
          -webkit-box-sizing: border-box;
          box-sizing: border-box;
          cursor: pointer;
          -webkit-tap-highlight-color: transparent;
        }

        .switch-button .switch-outer input[type="checkbox"] {
          opacity: 0;
          -webkit-appearance: none;
          -moz-appearance: none;
          appearance: none;
          position: absolute;
        }

        .switch-button .switch-outer .button-toggle {
          height: 42px;
          width: 42px;
          background: -webkit-gradient(
            linear,
            left top,
            left bottom,
            from(#3b3a4e),
            to(#272733)
          );
          background: -o-linear-gradient(#3b3a4e, #272733);
          background: linear-gradient(#3b3a4e, #272733);
          border-radius: 100%;
          -webkit-box-shadow: inset 0px 5px 4px 0px #424151, 0px 4px 15px 0px #0f0e17;
          box-shadow: inset 0px 5px 4px 0px #424151, 0px 4px 15px 0px #0f0e17;
          position: relative;
          z-index: 2;
          -webkit-transition: left 0.3s ease-in;
          -o-transition: left 0.3s ease-in;
          transition: left 0.3s ease-in;
          left: 0;
        }

        .switch-button
          .switch-outer
          input[type="checkbox"]:checked
          + .button
          .button-toggle {
          left: 58%;
        }

        .switch-button
          .switch-outer
          input[type="checkbox"]:checked
          + .button
          .button-indicator {
          -webkit-animation: indicator 1s forwards;
          animation: indicator 1s forwards;
        }

        .switch-button .switch-outer .button {
          width: 100%;
          height: 100%;
          display: -webkit-box;
          display: -ms-flexbox;
          display: flex;
          position: relative;
          -webkit-box-pack: justify;
          justify-content: space-between;
        }

        .switch-button .switch-outer .button-indicator {
          height: 25px;
          width: 25px;
          top: 50%;
          -webkit-transform: translateY(-50%);
          transform: translateY(-50%);
          border-radius: 50%;
          border: 3px solid #ef565f;
          -webkit-box-sizing: border-box;
          box-sizing: border-box;
          right: 10px;
          position: relative;
        }

        @-webkit-keyframes indicator {
          30% {
            opacity: 0;
          }

          0% {
            opacity: 1;
          }

          100% {
            opacity: 1;
            border: 3px solid #60d480;
            left: -68%;
          }
        }

        @keyframes indicator {
          30% {
            opacity: 0;
          }

          0% {
            opacity: 1;
          }

          100% {
            opacity: 1;
            border: 3px solid #60d480;
            left: -68%;
          }
        }

        .loader {
          width: 25px;
          height: 25px;
          position: relative;
          display: flex;
          align-items: center;
          justify-content: center;
          margin-right: 10px;
        }

        .loader_cube {
          position: absolute;
          width: 100%;
          height: 100%;
          border-radius: 5px;
        }

        .loader_cube--glowing {
          z-index: 2;
          background-color: rgba(255, 255, 255, 0.2);
          border: 1px solid rgba(255, 255, 255, 0.3);
        }

        .loader_cube--color {
          z-index: 1;
          filter: blur(0.5px);
          background: linear-gradient(135deg, #1afbf0, #da00ff);
          transform: rotate(45deg);
        }

        .custom-font {
          font-family: 'CangErYuMoW02-2', sans-serif;
          font-weight: 300;
        }

        #menu {
          position: absolute;
          top: 64px;
          right: 1rem;
          background: rgba(15, 15, 20, 0.9);
          backdrop-filter: blur(16px);
          border: 1px solid rgba(255, 255, 255, 0.08);
          border-radius: 0.5rem;
          padding: 1rem;
          z-index: 10;
        }

        @media (min-width: 1024px) {
          #menu {
            position: static;
            background: transparent;
            backdrop-filter: none;
            border: none;
            border-radius: 0;
            padding: 0;
          }
        }
    </style>
</head>
<body class="h-full text-gray-200 selection:bg-purple-500/30">
    <nav class="fixed w-full z-50 glass">
        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div class="flex items-center justify-between h-16">
                <div class="flex items-center">
                    <div class="loader">
                        <div class="loader_cube loader_cube--color"></div>
                        <div class="loader_cube loader_cube--glowing"></div>
                    </div>
                    <a href="/" class="text-xl font-bold gradient-text">OnePage</a>
                </div>
                <div class="lg:hidden">
                    <button onclick="toggleMenu()" class="text-white text-xl">☰</button>
                </div>
                <div id="menu" class="hidden lg:flex flex-col lg:flex-row items-start lg:items-center space-y-4 lg:space-y-0 lg:space-x-4 text-sm font-medium">
                    <?php if (isset($_SESSION['user_id'])): ?>
                        <?php if (($_SESSION['role'] ?? '') === 'admin'): ?>
                            <a href="/admin" class="text-purple-400 hover:text-purple-300">系统管理</a>
                        <?php endif; ?>
                        <a href="/dashboard" class="hover:text-white transition">工作台</a>
                        <a href="/profile" class="hover:text-white transition">个人资料</a>
                        <a href="/logout" class="px-4 py-2 rounded-full bg-white/10 hover:bg-white/20 transition">退出</a>
                    <?php else: ?>
                        <a href="/login" class="hover:text-white transition">登录</a>
                        <a href="/register" class="px-4 py-2 rounded-full bg-white text-black hover:bg-gray-200 transition">开启创作</a>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </nav>

    <main class="pt-16 min-h-full">
        <?= $content ?>
    </main>

    <footer class="py-12 border-t border-white/5 text-center text-gray-500 text-sm">
        <p>&copy; 2026 OnePage. Crafted with Passion.</p>
    </footer>
    <script>
        function toggleMenu() {
            var menu = document.getElementById('menu');
            menu.classList.toggle('hidden');
        }
    </script>
</body>
</html>
